name: Pinger Cron

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: curl -I https://altior-browser.onrender.com
